Susoft.CMS/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Susoft.Model;
using Susoft.CMS.Common;
using Susoft.CMS.Models;
namespace Susoft.CMS.Controllers
{
    public class CommonController : Controller
    {
        private SusoftCMSEntities db = new SusoftCMSEntities();
        // GET: Common
        public ActionResult Index()
        {
            return View();
        }
        [AllowAnonymous]
        [ChildActionOnly]
        public ActionResult GetMainMenu()
        {
            var categoryParent = db.Category.Where(x => x.Status == (int)CMS_STATUS.ACTIVE
              && x.IsMenu == true
              && (x.ParentId == -1||x.ParentId == null)).OrderBy(x => x.OrderBy).ToList(); ;

            var categoryChild = db.Category.Where(x => x.Status == (int)CMS_STATUS.ACTIVE
              && x.IsMenu == true
              && x.ParentId != -1 && x.ParentId != null).OrderBy(x => x.OrderBy).ToList();

            var ListCategoryForMenu = new List<CategoriesViewModel>();
            foreach (Category item in categoryParent)
            {
                CategoriesViewModel cateViewModel = new CategoriesViewModel();
                cateViewModel.categoryInfo = item;
                foreach (Category sub in categoryChild)
                {
                    if (cateViewModel.childCategory == null)
                    {
                        cateViewModel.childCategory = new List<Category>();
                    }
                    if (sub.ParentId == item.Id)
                    {
                        cateViewModel.childCategory.Add(sub);
                    }
                }
                ListCategoryForMenu.Add(cateViewModel);
            }
            ViewBag.ListCategoryForMenu = ListCategoryForMenu;
            return PartialView(ListCategoryForMenu);
        }
        [ChildActionOnly]
        public ActionResult GetSideBar()
        {
            var categoryChild = db.Category.Where(x=>x.Status == (int)CMS_STATUS.ACTIVE 
                && x.IsMenu == true
                && x.ParentId != -1 && 
                (x.Position == (int)MENU_POSITION.LEFT_MENU || x.Position == (int)MENU_POSITION.RIGHT_MENU)).OrderBy(x => x.OrderBy).ToList();
            ViewBag.ListCategoryChild = categoryChild;
            return PartialView(categoryChild);
        }
    }
}

Susoft.CMS/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Susoft.Model;
using Susoft.CMS.Common;
using System.Net;

namespace Susoft.CMS.Controllers
{
    public class ProjectController : BaseController
    {
        private SusoftCMSEntities db = new SusoftCMSEntities();

        // GET: Project
        public ActionResult Index()
        {
            IList<Products> lstProduct = db.Products.Where(x=>x.Status == (int)CMS_STATUS.ACTIVE).OrderBy(x=>x.UpdateAt).ToList();
            return View(lstProduct);
        }

        // GET: Project/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Products product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Susoft.CMS/Views/Project/Details.cshtml
@model Susoft.Model.Products

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutWithDetails.cshtml";
}
@section MainMenu{
    @{Html.RenderAction("GetMainMenu", "Common");}
}
@section SideBar{
    @{Html.RenderAction("GetSideBar", "Common");}
}
@{
    var lang = ViewContext.RouteData.Values["lang"] as string;
}
<!-- Page Title Area
     =========================== -->
<section class="page-title fix">
    <div class="container bb-bottom">
        <div class="row">
            <div class="col-md-12">
                <div class="page-title-content">
                    <h2 class="page-title">@Resources.GlobalRes.ProjectBreacumb</h2>
                    <span class="sub-title">@Resources.GlobalRes.ReadProjectSubTitle</span>
                </div>
                <div class="bread-cumb">
                    @if (lang == null || lang.Contains("en"))
                    {
                        <ul>
                            <li><a href="/en/home">@Resources.GlobalRes.Home</a></li>
                            <li><a href="/en/project">@Resources.GlobalRes.Project</a></li>
                        </ul>
                    }
                    else if (lang.Equals("vi"))
                    {
                        <ul>
                            <li><a href="/vi/home">@Resources.GlobalRes.Home</a></li>
                            <li><a href="/vi/project">@Resources.GlobalRes.Project</a></li>
                        </ul>
                    }
                    else
                    {
                        <ul>
                            <li><a href="/vi/home">@Resources.GlobalRes.Home</a></li>
                            <li><a href="/vi/project">@Resources.GlobalRes.Project</a></li>
                        </ul>
                    }
                </div>
                <!-- /.END OF BREAD CUMB -->
            </div>
        </div>
    </div>
</section>
<!-- End Of Page Title Area -->
<!-- Page Internal Content -->
<section class="page-internal-content">
    <div class="container">
        <div class="row">
            <!-- Content Section -->
            <div class="col-md-9 main-content">
                <!-- Single News Post -->
                <div class="sin-project">
                    <div class="news-content">
                        <div class="news-bio">
                            @if (lang == null || lang.Contains("en"))
                            {
                                <h2>@Model.Name_EN</h2>
                            }
                            else if (lang.Equals("vi"))
                            {
                                <h2>@Model.Name</h2>
                            }
                            else
                            {
                                <h2>@Model.Name_JP</h2>
                            }
                                <span class="news-meta">23rd March, 2016,   by <a href="#" class="author">Susoft</a></span>
                            </div>
                            @Html.Raw(Server.HtmlDecode(@Model.Description))
                        </div>
                        <div class="news-tags">
                            <p>
                                Tags:
                            </p>
                        </div>
                        @*<div class="news-tags">
                                @if (lang == null || lang.Contains("en"))
                                {
                                    <p>
                                        Tags: <a href=@Model.Category.URL_EN>@Model.Category.Name_EN,</a>
                                    </p>
                                }
                                else if (lang.Equals("vi"))
                                {
                                    <p>
                                        Tags: <a href=@Model.Category.URL>@Model.Category.Name,</a>
                                    </p>
                                }
                                else
                                {
                                    <p>
                                        Tags: <a href=@Model.Category.URL_JP>@Model.Category.Name_JP,</a>
                                    </p>
                                }
                            </div>*@
                    </div>
                </div>
                <!-- /.End Of Content Section -->
                <!-- Sidebar -->
                @*@{Html.RenderAction("GetSideBar", "Common");}*@
                <!-- /.End Of Sidebar -->
            </div>
        </div>
    </section>
    <!-- /.End Of Page Internal Content -->

Susoft.CMS/Views/Project/Index.cshtml
@using Susoft.Model;
@using Susoft.CMS.Common;
@model IList<Susoft.Model.Products>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutWithProject.cshtml";
}
@{var lang = ViewContext.RouteData.Values["lang"] as string;
}
@section MainMenu{
    @{Html.RenderAction("GetMainMenu", "Common");}
}

@section BreaCumb{
    <div class="col-md-12">
        <div class="page-title-content">
            <h2 class="page-title">@Resources.GlobalRes.ProjectBreacumb</h2>
            <span class="sub-title">@Resources.GlobalRes.ReadProjectSubTitle</span>
        </div>
        <div class="bread-cumb">
            @if (lang == null || lang.Contains("en"))
            {
                <ul>
                    <li><a href="/en/home">@Resources.GlobalRes.Home</a></li>
                    <li><a href="/en/project">@Resources.GlobalRes.Project</a></li>
                </ul>
            }
            else if (lang.Equals("vi"))
            {
                <ul>
                    <li><a href="/vi/home">@Resources.GlobalRes.Home</a></li>
                    <li><a href="/vi/project">@Resources.GlobalRes.Project</a></li>
                </ul>
            }
            else
            {
                <ul>
                    <li><a href="/vi/home">@Resources.GlobalRes.Home</a></li>
                    <li><a href="/vi/project">@Resources.GlobalRes.Project</a></li>
                </ul>
            }
        </div>
        <!-- /.END OF BREAD CUMB -->
    </div>
}
<!-- What We Area
    =========================== -->
<section class="works-area pb-130">
    <div class="container">
        <div class="row">
            @foreach (Products item in Model)
            {
          <!-- Single Work -->
                <div class="col-sm-3 col-sm-6">
                    <div class="single-work text-center sin-project">
                        <a class="work-thumb mb-35" href="@Url.Action("Details","Project",new {id=item.Id })">
                            <img src="@Utitlitys.ImagePath(item.ImageTitle,(int)CMS_IMAGE_TYPE.PRODUCT_TYPE)" style="height:240px; width:240px" alt="">
                            <div class="work-hover"></div>
                        </a>
                        <div class="work-excerp">
                            <a href="@Url.Action("Details","Project",new {id=item.Id })">
                                @if (lang == null || lang.Contains("en"))
                                {
                                    <h2>@item.Name_EN</h2>
                                }
                                else if (lang.Equals("vi"))
                                {
                                    <h2>@item.Name</h2>
                                }
                                else
                                {
                                    <h2>@item.Name_JP</h2>
                                }
                            </a>
                            <p>@Utitlitys.PlatformToString(item.Platform.Value)</p>
                        </div>
                    </div>
                </div>
            <!-- /. End Of Single Work -->
            }
        </div>
    </div>
</section>
<!-- /.End Of What We Do Area -->