Susoft.CMS/Models/CategoriesViewModel.cs
using Susoft.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Susoft.CMS.Models
{
    public class CategoriesViewModel
    {
        public Category categoryInfo { get; set; }
        public Category parentCategory { get; set; }
        public List<Category> childCategory { get; set; }

    }
}

Susoft.CMS/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Susoft.Model;
using System.Web.Mvc.Html;
using Susoft.CMS.Common;
using Susoft.CMS.Models;

namespace Susoft.CMS.Controllers
{
    [Authorize]
    public class CategoriesController : Controller
    {
        private SusoftCMSEntities db = new SusoftCMSEntities();

        // GET: Categories
        public ActionResult Index()
        {
            var lstData = db.Category.ToList();
            var lstNew = new List<CategoriesViewModel>();
            foreach(Category cate in lstData)
            {
                var cateViewModel = new CategoriesViewModel();
                cateViewModel.categoryInfo = cate;
                cateViewModel.parentCategory = db.Category.Find(cate.ParentId);   
                lstNew.Add(cateViewModel);
            }
            return View(lstNew);
        }
        [ChildActionOnly]
        public Category getCategory(int cateId)
        {
            Category category = db.Category.Find(cateId);
            return category;
        }
        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Category.Find(id);
            var cateModel = new CategoriesViewModel();
            cateModel.categoryInfo = category;
            cateModel.parentCategory = db.Category.Find(category.ParentId);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(cateModel);
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            ViewBag.Position = Utitlitys.PositionToList();
            ViewBag.Status = Utitlitys.StatusToList();
            ViewBag.CategoryId = new SelectList(db.Category.ToList(), "Id", "Name");
            return View();
        }
        
        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CategoriesViewModel category, FormCollection cl)
        {
            if (ModelState.IsValid)
            {
                category.categoryInfo.CreateAt = DateTime.Now;
                category.categoryInfo.CreateBy = User.Identity.Name;
                if (cl["IsMenu"]!=null&&(cl["IsMenu"]).ToString().Equals("on"))
                {
                    category.categoryInfo.IsMenu = true;
                } 
                else
                {
                    category.categoryInfo.IsMenu = false;
                }
                if (category.categoryInfo.ParentId == null)
                {
                    category.categoryInfo.ParentId = -1;
                }
                db.Category.Add(category.categoryInfo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.Position = Utitlitys.PositionToList();
            ViewBag.Status = Utitlitys.StatusToList();
            ViewBag.CategoryId = new SelectList(db.Category.ToList(), "Id", "Name");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Category.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            CategoriesViewModel viewModel = new CategoriesViewModel();
            viewModel.categoryInfo = category;
            return View(viewModel); 
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CategoriesViewModel category, FormCollection cl)
        {
            if (ModelState.IsValid)
            {
                category.categoryInfo.UpdateAt = DateTime.Now;
                category.categoryInfo.UpdateBy = User.Identity.Name;
                if (cl["IsMenu"]!=null && (cl["IsMenu"]).ToString().Equals("on"))
                {
                    category.categoryInfo.IsMenu = true;
                }
                else
                {
                    category.categoryInfo.IsMenu = false;
                }
                if (category.categoryInfo.ParentId == null)
                {
                    category.categoryInfo.ParentId = -1;
                }
                db.Entry(category.categoryInfo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Category.Find(id);
            var categoryModel = new CategoriesViewModel();
            categoryModel.categoryInfo = category;
            categoryModel.parentCategory = db.Category.Find(category.ParentId);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(categoryModel);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Category.Find(id);
            db.Category.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Susoft.CMS/Views/Categories/Create.cshtml
@using Susoft.CMS.Models;
@model CategoriesViewModel
    @{
        ViewBag.Title = "Create";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }

    <h2>Create</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Chuyên mục</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <label class="control-label col-md-2">Chuyên mục cha</label>
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.categoryInfo.ParentId, (SelectList)ViewBag.CategoryId,"---Chuyên mục cha---", new { @class = "form-control", @style = "witdth:150px;" })
                    @Html.ValidationMessageFor(model => model.categoryInfo.ParentId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Tên chuyên mục</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.categoryInfo.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.categoryInfo.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Tên tiếng Anh</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.categoryInfo.Name_EN, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.categoryInfo.Name_EN, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Tên tiếng Nhật</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.categoryInfo.Name_JP, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.categoryInfo.Name_JP, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Link liên kết</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.categoryInfo.URL, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.categoryInfo.URL, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Link tiếng Anh</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.categoryInfo.URL_EN, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.categoryInfo.URL_EN, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Link tiếng Nhật</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.categoryInfo.URL_JP, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.categoryInfo.URL_JP, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Là Menu</label>
                <div class="col-md-10">
                        <input name="IsMenu" type="checkbox" /> 
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Trạng thái</label>
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.categoryInfo.Status, (SelectList)ViewBag.Status, new { @class = "form-control", @style = "witdth:150px;" })
                    @Html.ValidationMessageFor(model => model.categoryInfo.Status, "", new { @class = "text-danger" })
                </div>
            </div>
            
            <div class="form-group">
                <label class="control-label col-md-2">Vị trí</label>
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.categoryInfo.Position, (SelectList)ViewBag.Position, new { @class = "form-control", @style = "witdth:150px;" })
                    @Html.ValidationMessageFor(model => model.categoryInfo.Position, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">OrderBy</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.categoryInfo.OrderBy, new { @class = "form-control", @style = "witdth:150px;" })
                    @Html.ValidationMessageFor(model => model.categoryInfo.OrderBy, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>


    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

Susoft.CMS/Views/Categories/Delete.cshtml
@using Susoft.CMS.Common;
@using Susoft.CMS.Models;
@model CategoriesViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutBackEnd.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Chuyên mục</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên chuyên mục
        </dt>
        <dd>
            @Html.DisplayFor(m => m.categoryInfo.Name)
        </dd>

        <dt>
            Tên tiếng Anh
        </dt>
        <dd>
            @Html.DisplayFor(m => m.categoryInfo.Name_EN)
        </dd>

        <dt>
            Tên tiếng Nhật
        </dt>
        <dd>
            @Html.DisplayFor(m => m.categoryInfo.Name_JP)
        </dd>

        <dt>
            Link liên kết
        </dt>
        <dd>
            @Html.DisplayFor(m => m.categoryInfo.URL)
        </dd>

        <dt>
            Link tiếng Anh
        </dt>
        <dd>
            @Html.DisplayFor(m => m.categoryInfo.URL_EN)
        </dd>

        <dt>
            Link tiếng Nhật
        </dt>
        <dd>
            @Html.DisplayFor(m => m.categoryInfo.URL_JP)
        </dd>

        <dt>
           Menu
        </dt>

        <dd>
            @Model.categoryInfo.IsMenu.ToString()
        </dd>

        <dt>
            Trạng thái
        </dt>

        <dd>
            @Utitlitys.StatusToString(Model.categoryInfo.Status.Value)
        </dd>

        <dt>
            Chuyên mục cha
        </dt>

        <dd>
            @if (Model.parentCategory == null)
            {
                <span> --- </span>
            }
            else
            {
                @Html.DisplayFor(modelItem => Model.parentCategory.Name)
            }
        </dd>

        <dt>
           Người tạo
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoryInfo.CreateBy)
        </dd>

        <dt>
            Ngày tạo
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoryInfo.CreateAt)
        </dd>

        <dt>
            Cập nhật bởi
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoryInfo.UpdateBy)
        </dd>

        <dt>
            Ngày cập nhật
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoryInfo.UpdateAt)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Susoft.CMS/Views/Categories/Details.cshtml
@using Susoft.CMS.Common;
@using Susoft.CMS.Models;
@model CategoriesViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutBackEnd.cshtml";
}

<h2>Chi tiết chuyên mục</h2>

<div>
    <h4>Chuyên mục</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên chuyên mục
        </dt>
        <dd>
            @Html.DisplayFor(m => m.categoryInfo.Name)
        </dd>

        <dt>
            Tên tiếng Anh
        </dt>
        <dd>
            @Html.DisplayFor(m => m.categoryInfo.Name_EN)
        </dd>

        <dt>
            Tên tiếng Nhật
        </dt>
        <dd>
            @Html.DisplayFor(m => m.categoryInfo.Name_JP)
        </dd>

        <dt>
           Link liên kết
        </dt>
        <dd>
            @Html.DisplayFor(m => m.categoryInfo.URL)
        </dd>

        <dt>
            Link tiếng Anh
        </dt>
        <dd>
            @Html.DisplayFor(m => m.categoryInfo.URL_EN)
        </dd>

        <dt>
            Link tiếng Nhật
        </dt>
        <dd>
            @Html.DisplayFor(m => m.categoryInfo.URL_JP)
        </dd>
            
        <dt>
           Menu
        </dt>

        <dd>
            @Model.categoryInfo.IsMenu.ToString()
        </dd>

        <dt>
           Trạng thái
        </dt>

        <dd>
            @Utitlitys.StatusToString(Model.categoryInfo.Status.Value)
        </dd>

        <dt>
           Chuyên mục cha
        </dt>

        <dd>
           @*@Html.DisplayFor(model => model.ParentId)*@
           @if (Model.parentCategory == null)
            {
            <span> --- </span>
           }
           else
           {
            @Html.DisplayFor(modelItem => Model.parentCategory.Name)
           }
        </dd>

        <dt>
            Người tạo
            @*@Html.DisplayNameFor(model => model.CreateBy)*@
        </dt>

        <dd>
            @Html.DisplayFor(m => m.categoryInfo.CreateBy)
        </dd>

        <dt>
            Ngày tạo
        </dt>

        <dd>
            @Html.DisplayFor(m => m.categoryInfo.CreateAt)
        </dd>

        <dt>
            Cập nhật bởi
        </dt>

        <dd>
            @Html.DisplayFor(m => m.categoryInfo.UpdateBy)
        </dd>

        <dt>
            Ngày cập nhật
        </dt>

        <dd>
            @Html.DisplayFor(m => m.categoryInfo.UpdateAt)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.categoryInfo.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Susoft.CMS/Views/Categories/Edit.cshtml
@using Susoft.CMS.Models;
@model CategoriesViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Sửa thông tin</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Chuyên mục</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.categoryInfo.Id)

        <div class="form-group">
            <label class="control-label col-md-2" for="Name">Tên chuyên mục</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.categoryInfo.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.categoryInfo.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2" for="Name">Tên tiếng Anh</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.categoryInfo.Name_EN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.categoryInfo.Name_EN, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2" for="Name">Tên tiếng Nhật</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.categoryInfo.Name_JP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.categoryInfo.Name_JP, "", new { @class = "text-danger" })
            </div>
        </div>
     
        <div class="form-group">
            <label class="control-label col-md-2" for="URL">Linh liên kết</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.categoryInfo.URL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.categoryInfo.URL, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2" for="URL">Linh liên kết tiếng Anh</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.categoryInfo.URL_EN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.categoryInfo.URL_EN, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2" for="URL">Linh liên kết tiếng Nhật</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.categoryInfo.URL_JP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.categoryInfo.URL_JP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Type">Menu</label>
            <div class="col-md-10">
                <input name="IsMenu" type="checkbox"  />     
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Status">Trạng thái</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.categoryInfo.Status, (SelectList)ViewBag.Status, new { @class = "form-control", @style = "witdth:150px;" })
                @Html.ValidationMessageFor(model => model.categoryInfo.Status, "", new { @class = "text-danger" }) 
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="ParentId">Chuyên mục cha</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.categoryInfo.ParentId, (SelectList)ViewBag.CategoryId, "---Chuyên mục cha---", new { @class = "form-control", @style = "witdth:150px;" })
                @Html.ValidationMessageFor(model => model.categoryInfo.ParentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="URL">Vị Trí</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.categoryInfo.Position, (SelectList)ViewBag.Position, new { @class = "form-control", @style = "witdth:150px;" })
                @Html.ValidationMessageFor(model => model.categoryInfo.Position, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="URL">OrderBy</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.categoryInfo.OrderBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.categoryInfo.OrderBy, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Susoft.CMS/Views/Categories/Index.cshtml
@using Susoft.CMS.Common;
@using Susoft.CMS.Models;
@*@using Susoft.CMS.Controllers;*@
@model IEnumerable<CategoriesViewModel> 

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutBackEnd.cshtml";
    //var controller = ViewContext.Controller as CategoriesController;
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Tên chuyên mục
        </th>
        <th>
            Link liên kết
        </th>
        <th>
            Menu
        </th>
        <th>
            Trạng thái
        </th>
        <th>
            Chuyên mục cha
        </th>
        <th>
            Vị trí
        </th>
        <th>
            OrderBy
        </th>
        <th>
            Người tạo
        </th>
        <th>
            Ngày tạo
        </th>
        <th></th>
        <th>
            Ngày cập nhật
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td style="width:250px">
                <a href="@Url.Action("Details", new { id = item.categoryInfo.Id })">@Html.DisplayFor(modelItem => item.categoryInfo.Name)</a>
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.categoryInfo.Name_EN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.categoryInfo.Name_JP)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.categoryInfo.URL)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.categoryInfo.URL_EN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.categoryInfo.URL_JP)
            </td>*@
            <td>
                @item.categoryInfo.IsMenu.ToString()
            </td>
            <td>
               @Utitlitys.StatusToString(item.categoryInfo.Status.Value)
            </td>
            <td>
              @*@controller.getCategory(item.ParentId.Value).Name*@
                @if (item.parentCategory == null)
                {
                    <span> --- </span>
                }
                else
                {
                    @Html.DisplayFor(modelItem => item.parentCategory.Name)
                }
           
            </td>
            <td>
                @Utitlitys.PositionToString(item.categoryInfo.Position.Value)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.categoryInfo.OrderBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.categoryInfo.CreateBy)
            </td>
            <td>
               @item.categoryInfo.CreateAt
                @*@Utitlitys.DatetimeToVN(item.categoryInfo.CreateAt.Value)*@
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.UpdateBy)*@    
            </td>
            <td>
                @item.categoryInfo.UpdateAt
                @*@Html.DisplayFor(modelItem => item.UpdateAt)*@
            </td>
            <td style="white-space:nowrap">
                <a href='@Url.Action("Edit", "Categories", new { id = item.categoryInfo.Id })'><img src="~/img/icons/page_white_edit.png" title="Cập nhật" /></a> |
                <a href='@Url.Action("Delete", "Categories",new { id = item.categoryInfo.Id })'><img src="~/img/icons/bin_closed.png" title="Xóa thông tin" /></a>
            </td>
        </tr>
    }

</table>