Susoft.CMS/Models/ArticleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Susoft.Model;
namespace Susoft.CMS.Models
{
    public class ArticleViewModel
    {
        public Articles articleInfo { get; set; }
        public List<SelectListItem> statusArticles { get; set; }
        [AllowHtml]
        public string Description { get; set; }
        [AllowHtml]
        public string Description_EN { get; set; }
        [AllowHtml]
        public string Description_JP { get; set; }

        [AllowHtml]
        public string Summary { get; set; }
        //public bool isHotNew { get; set; }
        [AllowHtml]
        public string Summary_EN { get; set; }
        [AllowHtml]
        public string Summary_JP { get; set; }
    }
}

Susoft.CMS/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Susoft.Model;
using Susoft.CMS.Common;
using Susoft.CMS.Models;
using System.Web.Mvc.Html;
using System.IO;

namespace Susoft.CMS.Controllers
{
    [Authorize]
    public class ArticlesController : Controller
    {
        private SusoftCMSEntities db = new SusoftCMSEntities();

        // GET: Articles
        public ActionResult Index()
        {
            var articles = db.Articles.Include(a => a.Category);
            return View(articles.ToList());
        }

        // GET: Articles/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Articles articles = db.Articles.Find(id);
            if (articles == null)
            {
                return HttpNotFound();
            }
            return View(articles);
        }

        // GET: Articles/Create
        public ActionResult Create()
        {
            ViewBag.Status = Utitlitys.StatusToList();
            ViewBag.CategoryId = new SelectList(db.Category, "Id", "Name");
            return View();
        }

        // POST: Articles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create(ArticleViewModel articles, IEnumerable<HttpPostedFileBase> files, FormCollection cl)
        {
            if (ModelState.IsValid)
            {
                if (cl["HotNew"]!= null && (cl["HotNew"]).Equals("on"))
                {
                    articles.articleInfo.HotNew = true;
                }
                else
                {
                    articles.articleInfo.HotNew = false;
                }
                var fileName = string.Empty;
                if (files != null)
                {
                    foreach (var file in files)
                    {
                        if (file != null && file.ContentLength > 0)
                        {
                            //kiem tra file extension lan nua
                            List<string> excelExtension = new List<string>();
                            excelExtension.Add(".png");
                            excelExtension.Add(".jpg");
                            excelExtension.Add(".gif");
                            var extension = Path.GetExtension(file.FileName);
                            if (!excelExtension.Contains(extension.ToLower()))
                            {
                                return Json(new { success = 0, message = "File không đúng định dạng cho phép, bạn hãy chọn file có định dạng .jpg, gif hoặc png" });
                            }
                            //kiem tra dung luong file
                            var fileSize = file.ContentLength;
                            var fileMB = (fileSize / 1024f) / 1024f;
                            if (fileMB > 5)
                            {
                                return Json(new { success = 0, message = "Dung lượng ảnh không được lớn hơn 5MB" });
                            }
                            // luu ra dia
                            fileName = Path.GetFileNameWithoutExtension(file.FileName);
                            //fileName = fileName + "_" + user.UserID + extension;
                            fileName = fileName + extension;
                            var physicalPath = Path.Combine(Server.MapPath("~/Uploads/TinTuc"), fileName);
                            file.SaveAs(physicalPath);
                            articles.articleInfo.ThumbURL = fileName;
                        }
                    }
                }
                articles.articleInfo.Summary = articles.Summary;
                articles.articleInfo.Summary_EN = articles.Summary_EN;
                articles.articleInfo.Summary_JP = articles.Summary_JP;
                articles.articleInfo.Description = articles.Description;
                articles.articleInfo.Description_EN = articles.Description_EN;
                articles.articleInfo.Description_JP = articles.Description_JP;
                articles.articleInfo.CreateAt = DateTime.Now;
                articles.articleInfo.CreateBy = User.Identity.Name;
                articles.articleInfo.Category = db.Category.Find(articles.articleInfo.CategoryId);
                //articles.articleInfo.HotNew = articles.isHotNew;
                db.Articles.Add(articles.articleInfo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.Category, "Id", "Name", articles.articleInfo.CategoryId);
            return View(articles);
        }

        // GET: Articles/Edit/5
        public ActionResult Edit(long? id)
        {
            ViewBag.Status = Utitlitys.StatusToList();
            ViewBag.CategoryId = new SelectList(db.Category, "Id", "Name");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Articles articles = db.Articles.Find(id);
            if (articles == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Category, "Id", "Name", articles.CategoryId);
            ArticleViewModel viewmodel = new ArticleViewModel();
            viewmodel.articleInfo = articles;
            viewmodel.Description = articles.Description;
            viewmodel.Description_EN = articles.Description_EN;
            viewmodel.Description_JP = articles.Description_JP;
            viewmodel.Summary = articles.Summary;
            viewmodel.Summary_EN = articles.Summary_EN;
            viewmodel.Summary_JP = articles.Summary_JP;
            return View(viewmodel);
        }

        // POST: Articles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ArticleViewModel articles, IEnumerable<HttpPostedFileBase> files, FormCollection cl)
        {
            if (ModelState.IsValid)
            {
                if (cl["HotNew"] != null && (cl["HotNew"]).Equals("on"))
                {
                    articles.articleInfo.HotNew = true;
                }
                else
                {
                    articles.articleInfo.HotNew = false;
                }
                var old = db.Articles.Find(articles.articleInfo.Id);
                var fileName = string.Empty;
                if (files != null)
                {
                    foreach (var file in files)
                    {
                        if (file != null && file.ContentLength > 0)
                        {
                            //kiem tra file extension lan nua
                            List<string> excelExtension = new List<string>();
                            excelExtension.Add(".png");
                            excelExtension.Add(".jpg");
                            excelExtension.Add(".gif");
                            var extension = Path.GetExtension(file.FileName);
                            if (!excelExtension.Contains(extension.ToLower()))
                            {
                                return Json(new { success = 0, message = "File không đúng định dạng cho phép, bạn hãy chọn file có định dạng .jpg, gif hoặc png" });
                            }
                            //kiem tra dung luong file
                            var fileSize = file.ContentLength;
                            var fileMB = (fileSize / 1024f) / 1024f;
                            if (fileMB > 5)
                            {
                                return Json(new { success = 0, message = "Dung lượng ảnh không được lớn hơn 5MB" });
                            }
                            if (old.ThumbURL != null)
                            {
                                fileName = old.ThumbURL;
                            }
                            else
                            {
                                // luu ra dia
                                fileName = Path.GetFileNameWithoutExtension(file.FileName);
                                //fileName = fileName + "_" + user.UserID + extension;
                                fileName = fileName + extension;
                            }

                            var physicalPath = Path.Combine(Server.MapPath("~/Uploads/TinTuc"), fileName);
                            file.SaveAs(physicalPath);
                            articles.articleInfo.ThumbURL = fileName;
                            old.ThumbURL = articles.articleInfo.ThumbURL;
                        }
                    }
                }
                articles.articleInfo.Category = db.Category.Find(articles.articleInfo.CategoryId);
                old.Category = articles.articleInfo.Category;
                old.Status = articles.articleInfo.Status;
                old.HotNew = articles.articleInfo.HotNew;
                old.Title = articles.articleInfo.Title;
                old.Title_EN = articles.articleInfo.Title_EN;
                old.Title_JP = articles.articleInfo.Title_JP;
                old.UpdateAt = DateTime.Now;
                old.UpdateBy = User.Identity.Name;
                old.Summary = articles.Summary;
                old.Description = articles.Description;
                old.Summary_EN = articles.Summary_EN;

Susoft.CMS/Views/Articles/Create.cshtml
@using Susoft.Model;
@model Susoft.CMS.Models.ArticleViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutBackEnd.cshtml";
}
@section HeaderScript{
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
    <link href="~/Content/Bootstrap.min.css" rel="stylesheet" />
}
<h2>Thêm mới bài viết</h2>

@using (Html.BeginForm("Create", "Articles", FormMethod.Post, new { enctype = "multipart/form-data", id = "frmCreate" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Quản lý bài viết</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Tiêu đề</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.articleInfo.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.articleInfo.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Tiêu đề tiếng Anh</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.articleInfo.Title_EN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.articleInfo.Title_EN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Tiêu đề tiếng Nhật</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.articleInfo.Title_JP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.articleInfo.Title_JP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Chuyên mục</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.articleInfo.CategoryId, (SelectList)ViewBag.CategoryId, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.articleInfo.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Tóm tắt</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Summary, new { @id = "Summary" })
                <script>
                    // Replace the <textarea id="editor1"> with a CKEditor
                    // instance, using default configuration.
                    CKEDITOR.replace('Summary', {
                        filebrowserBrowseUrl: '/CKFinderScripts/ckfinder.html',
                        filebrowserImageBrowseUrl: '/CKFinderScripts/ckfinder.html?type=Images',
                        filebrowserUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Files',
                        filebrowserImageUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Images'
                    });
                </script>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Tóm tắt tiếng Anh</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Summary_EN, new { @id = "Summary_EN" })
                <script>
                    // Replace the <textarea id="editor1"> with a CKEditor
                    // instance, using default configuration.
                    CKEDITOR.replace('Summary_EN', {
                        filebrowserBrowseUrl: '/CKFinderScripts/ckfinder.html',
                        filebrowserImageBrowseUrl: '/CKFinderScripts/ckfinder.html?type=Images',
                        filebrowserUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Files',
                        filebrowserImageUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Images'
                    });
                </script>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Tóm tắt tiếng Nhật</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Summary_JP, new { @id = "Summary_JP" })
                <script>
                    // Replace the <textarea id="editor1"> with a CKEditor
                    // instance, using default configuration.
                    CKEDITOR.replace('Summary_JP', {
                        filebrowserBrowseUrl: '/CKFinderScripts/ckfinder.html',
                        filebrowserImageBrowseUrl: '/CKFinderScripts/ckfinder.html?type=Images',
                        filebrowserUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Files',
                        filebrowserImageUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Images'
                    });
                </script>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Chi tiết bài viết</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { @id = "Description" })
                <script>
                    // Replace the <textarea id="editor1"> with a CKEditor
                    // instance, using default configuration.
                    CKEDITOR.replace('Description', {
                        filebrowserBrowseUrl: '/CKFinderScripts/ckfinder.html',
                        filebrowserImageBrowseUrl: '/CKFinderScripts/ckfinder.html?type=Images',
                        filebrowserUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Files',
                        filebrowserImageUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Images'
                    });
                </script>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Chi tiết tiếng Anh</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description_EN, new { @id = "Description_EN" })
                <script>
                    // Replace the <textarea id="editor1"> with a CKEditor
                    // instance, using default configuration.
                    CKEDITOR.replace('Description_EN', {
                        filebrowserBrowseUrl: '/CKFinderScripts/ckfinder.html',
                        filebrowserImageBrowseUrl: '/CKFinderScripts/ckfinder.html?type=Images',
                        filebrowserUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Files',
                        filebrowserImageUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Images'
                    });
                </script>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Chi tiết tiếng Nhật</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description_JP, new { @id = "Description_JP" })
                <script>
                    // Replace the <textarea id="editor1"> with a CKEditor
                    // instance, using default configuration.
                    CKEDITOR.replace('Description_JP', {
                        filebrowserBrowseUrl: '/CKFinderScripts/ckfinder.html',
                        filebrowserImageBrowseUrl: '/CKFinderScripts/ckfinder.html?type=Images',
                        filebrowserUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Files',
                        filebrowserImageUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Images'
                    });
                </script>
            </div>
        </div>


        <div class="form-group">
            <label class="control-label col-md-2">Ảnh tiêu đề</label>
            <div class="col-md-10">
                <input type="file" name="files" id="files" style="width: 100%;" /><br>
                <i style="font-size: 11px; font-style: italic;">File ảnh có định dạng .png, gif hoặc .jpg</i><br>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Tin nóng</label>
            <div class="col-md-10">
                <input name="HotNew" type="checkbox" />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Trạng thái</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.articleInfo.Status, (SelectList)ViewBag.Status, new { @class = "form-control", @style = "witdth:150px;" })
                @Html.ValidationMessageFor(model => model.articleInfo.Status, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script type="text/javascript">
    $('#frmCreate').on('submit', function () {
        for (instance in CKEDITOR.instances) {
            CKEDITOR.instances[instance].updateElement();
        }
    });
</script>

Susoft.CMS/Views/Articles/Edit.cshtml
@model Susoft.CMS.Models.ArticleViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutBackEnd.cshtml";
}
@section HeaderScript{
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
    <link href="~/Content/Bootstrap.min.css" rel="stylesheet" />
}

<h2>Sửa tin bài</h2>
@using (Html.BeginForm("Edit", "Articles", FormMethod.Post, new { enctype = "multipart/form-data", id = "frmCreate" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.articleInfo.Id)

    <div class="form-horizontal">
        <h4>Quản lý bài viết</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.articleInfo.Id)

        <div class="form-group">
            <label class="control-label col-md-2">Tiêu đề</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.articleInfo.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.articleInfo.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Tiêu đề tiếng Anh</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.articleInfo.Title_EN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.articleInfo.Title_EN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Tiêu đề tiếng Nhật</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.articleInfo.Title_JP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.articleInfo.Title_JP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Tóm tắt</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Summary, new { @id = "Summary" })
                <script>

                    // Replace the <textarea id="editor1"> with a CKEditor
                    // instance, using default configuration.
                    CKEDITOR.replace('Summary', {
                        filebrowserBrowseUrl: '/CKFinderScripts/ckfinder.html',
                        filebrowserImageBrowseUrl: '/CKFinderScripts/ckfinder.html?type=Images',
                        filebrowserUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Files',
                        filebrowserImageUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Images'
                    });
                </script>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Tóm tắt tiếng Anh</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Summary_EN, new { @id = "Summary_EN" })
                <script>

                    // Replace the <textarea id="editor1"> with a CKEditor
                    // instance, using default configuration.
                    CKEDITOR.replace('Summary_EN', {
                        filebrowserBrowseUrl: '/CKFinderScripts/ckfinder.html',
                        filebrowserImageBrowseUrl: '/CKFinderScripts/ckfinder.html?type=Images',
                        filebrowserUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Files',
                        filebrowserImageUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Images'
                    });
                </script>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Tóm tắt tiếng Nhật</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Summary_JP, new { @id = "Summary_JP" })
                <script>

                    // Replace the <textarea id="editor1"> with a CKEditor
                    // instance, using default configuration.
                    CKEDITOR.replace('Summary_JP', {
                        filebrowserBrowseUrl: '/CKFinderScripts/ckfinder.html',
                        filebrowserImageBrowseUrl: '/CKFinderScripts/ckfinder.html?type=Images',
                        filebrowserUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Files',
                        filebrowserImageUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Images'
                    });
                </script>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Chi tiết bài viết</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { @id = "Description" })

                <script>
                    // Replace the <textarea id="editor1"> with a CKEditor
                    // instance, using default configuration.
                    CKEDITOR.replace('Description', {
                        filebrowserBrowseUrl: '/CKFinderScripts/ckfinder.html',
                        filebrowserImageBrowseUrl: '/CKFinderScripts/ckfinder.html?type=Images',
                        filebrowserUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Files',
                        filebrowserImageUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Images'
                    });
                </script>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Chi tiết tiếng Anh</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description_EN, new { @id = "Description_EN" })

                <script>
                    // Replace the <textarea id="editor1"> with a CKEditor
                    // instance, using default configuration.
                    CKEDITOR.replace('Description_EN', {
                        filebrowserBrowseUrl: '/CKFinderScripts/ckfinder.html',
                        filebrowserImageBrowseUrl: '/CKFinderScripts/ckfinder.html?type=Images',
                        filebrowserUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Files',
                        filebrowserImageUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Images'
                    });
                </script>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Chi tiết tiếng Nhật</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description_JP, new { @id = "Description_JP" })

                <script>
                    // Replace the <textarea id="editor1"> with a CKEditor
                    // instance, using default configuration.
                    CKEDITOR.replace('Description_JP', {
                        filebrowserBrowseUrl: '/CKFinderScripts/ckfinder.html',
                        filebrowserImageBrowseUrl: '/CKFinderScripts/ckfinder.html?type=Images',
                        filebrowserUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Files',
                        filebrowserImageUploadUrl: '/CKFinderScripts/connector?command=QuickUpload&type=Images'
                    });
                </script>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Chuyên mục</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.articleInfo.CategoryId, (SelectList)ViewBag.CategoryId, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.articleInfo.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Ảnh tiêu đề</label>
            <div class="col-md-10">
                <input type="file" name="files" id="files" style="width: 100%;" /><br>
                <i style="font-size: 11px; font-style: italic;">File ảnh có định dạng .png, gif hoặc .jpg</i><br>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Tin nóng</label>
            <div class="col-md-10">
              <input name="HotNew" type="checkbox" />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Trạng thái</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.articleInfo.Status, (SelectList)ViewBag.Status, new { @class = "form-control", @style = "witdth:150px;" })
                @Html.ValidationMessageFor(model => model.articleInfo.Status, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script type="text/javascript">
    $('#frmCreate').on('submit', function () {
        for (instance in CKEDITOR.instances) {
            CKEDITOR.instances[instance].updateElement();
        }
    });
</script>